### ISSUE TITLE
Instructions for CPUSim installation no longer seem to work for Ubuntu.

### ISSUE THREAD

**Issue by AetherPrior** [Colby-CPU-Sim/CPUSim#117]
Over the past 2 or 3 years, Java has changed quite a bit, and JavaFx is no longer shipped with java. As a result, the jfxrt.jar is missing from the java installations, which results in the application no longer starting.

**Comment by djskrien** [comment]
You are correct. CPU Sim needs updating to handle the latest versions of Java.  In the meanwhile, you should use CPU Sim only with Java 8, which includes jfxrt.jar.

Dale

**Comment by mgood7123** [comment]
i tried this with zulu-java with javafx

```
smallville7123@smallville7123-MacBookPro:~/CPUSim4.0.11$ ls /usr/lib/jvm
zulu-14-amd64  zulu-8-amd64
smallville7123@smallville7123-MacBookPro:~/CPUSim4.0.11$ ls /usr/lib/jvm/*
/usr/lib/jvm/zulu-14-amd64:
bin   demo        include  legal  man              readme.txt  Welcome.html
conf  DISCLAIMER  jmods    lib    OPENJFX_LICENSE  release

/usr/lib/jvm/zulu-8-amd64:
ASSEMBLY_EXCEPTION        include  OPENJFX_LICENSE             sample
bin                       jre      openjfx-src.zip             src.zip
CLASSPATH_EXCEPTION_NOTE  lib      OPENJFX_THIRD_PARTY_README  THIRD_PARTY_README
demo                      LICENSE  readme.txt                  Welcome.html
DISCLAIMER                man      release
smallville7123@smallville7123-MacBookPro:~/CPUSim4.0.11$ find /usr/lib/jvm/ -name jfxrt.jar
/usr/lib/jvm/zulu-8-amd64/jre/lib/ext/jfxrt.jar
smallville7123@smallville7123-MacBookPro:~/CPUSim4.0.11$ 
```
and got

```
smallville7123@smallville7123-MacBookPro:~/CPUSim4.0.11$ java -cp .:richtextfx-fat-0.6.10.jar:reactfx-2.0-MR.jar -jar CPUSim-4.0.11.jar
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.fxmisc.richtext.skin.TextFlowExt (file:/home/smallville7123/CPUSim4.0.11/richtextfx-0.6.10.jar) to method javafx.scene.text.TextFlow.getTextLayout()
WARNING: Please consider reporting this to the maintainers of org.fxmisc.richtext.skin.TextFlowExt
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Exception in Application start method
Exception in thread "main" java.lang.RuntimeException: Exception in Application start method
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:900)
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
        at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.lang.NoSuchMethodError: 'javafx.beans.property.ObjectProperty org.fxmisc.richtext.skin.TextExt.impl_selectionFillProperty()'
        at org.fxmisc.richtext.skin.ParagraphText.<init>(ParagraphText.java:108)
        at org.fxmisc.richtext.skin.ParagraphBox.<init>(ParagraphBox.java:74)
        at org.fxmisc.richtext.skin.StyledTextAreaView.createCell(StyledTextAreaVisual.java:396)
        at org.fxmisc.richtext.skin.StyledTextAreaView.lambda$new$117(StyledTextAreaVisual.java:146)
        at org.fxmisc.flowless.CellPool.getCell(CellPool.java:20)
        at org.fxmisc.flowless.CellListManager.cellForItem(CellListManager.java:75)
        at org.reactfx.collection.MappedList.get(MappedList.java:27)
        at org.reactfx.collection.MemoizationListImpl.get(MemoizationList.java:99)
        at org.fxmisc.flowless.CellListManager.getCell(CellListManager.java:64)
        at org.fxmisc.flowless.CellPositioner.getSizedCell(CellPositioner.java:129)
        at org.fxmisc.flowless.CellPositioner.placeStartAt(CellPositioner.java:95)
        at org.fxmisc.flowless.Navigator.placeStartAtMayCrop(Navigator.java:181)
        at org.fxmisc.flowless.Navigator.visit(Navigator.java:109)
        at org.fxmisc.flowless.StartOffStart.accept(TargetPosition.java:49)
        at org.fxmisc.flowless.Navigator.layoutChildren(Navigator.java:66)
        at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1207)
        at org.fxmisc.flowless.VirtualFlowContent.layoutChildren(VirtualFlowContent.java:118)
        at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1207)
        at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1214)
        at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1214)
        at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1214)
        at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1214)
        at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1214)
        at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1214)
        at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1214)
        at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1214)
        at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1214)
        at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1214)
        at javafx.graphics/javafx.scene.Scene.doLayoutPass(Scene.java:576)
        at javafx.graphics/javafx.scene.Scene.preferredSize(Scene.java:1784)
        at javafx.graphics/javafx.scene.Scene$2.preferredSize(Scene.java:393)
        at javafx.graphics/com.sun.javafx.scene.SceneHelper.preferredSize(SceneHelper.java:66)
        at javafx.graphics/javafx.stage.Window$12.invalidated(Window.java:1086)
        at javafx.base/javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:110)
        at javafx.base/javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:145)
        at javafx.graphics/javafx.stage.Window.setShowing(Window.java:1174)
        at javafx.graphics/javafx.stage.Window.show(Window.java:1189)
        at javafx.graphics/javafx.stage.Stage.show(Stage.java:273)
        at cpusim.GUIMain.start(GUIMain.java:91)
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:846)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:455)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
        at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
        at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
        at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
        ... 1 more
```

**Comment by djskrien** [comment]
Hello,

Which version of Java are you using?  You need to use Java 8 or earlier for CPU Sim.

Dale

**Comment by AetherPrior** [comment]
By Java 8, you mean Oracle Java right?

**Comment by AetherPrior** [comment]
Meanwhile, shall I close this issue, and open an another issue for the same?  
Looks like this problem has existed since the time JavaFX stopped shipping with Java.

**Comment by djskrien** [comment]
Yes, I mean Oracle Java SE 8.

Dale

**Comment by djskrien** [comment]
Yes, that would be a good idea.

Dale
